### ISSUE TITLE
Dedicated Julia package ?

### ISSUE THREAD

**Issue by aTrotier** [mfuderer/colorResources#6]
Should we create a dedicated julia package ?

it is also possible to directly add it to some colorpackage like ColorSchemes.jl (used by makie) : https://github.com/JuliaGraphics/ColorSchemes.jl/tree/master/data 

IMO, a dedicated package seems better because we can add the post-processing dedicated to each qMRI maps. It will be more flexible / visible to the MRCommunity (especially if we add it to the https://github.com/MagneticResonanceImaging)

**Comment by aTrotier** [comment]
WIP here : https://github.com/aTrotier/qMRIColors.jl

**Comment by mfuderer** [comment]
Hi Aurelien,
I strongly appreciate your initiative!
Could you add oscarvanderheide as well as me as developers to that package?
I would like to add explanations to the readme.md. This might take a week or two, though. Please be patient.
Best,
Miha

________________________________

**Comment by aTrotier** [comment]
Done, maybe you will loose the admin rights when I will move the package to [MagneticResonanceImaging](https://github.com/MagneticResonanceImaging). I will add you again if needed.

Anyway, even without the admin rights you can fork and create a pull request
